#!/usr/bin/env zsh --no-rcs

optKeyDown=`./keys option`
shiftKeyDown=`./keys shift`

for f in "$@"
do
	if [ $optKeyDown -eq 0 ]
	then
		printf "$f\n\n"
	else
		b=`basename "$f"`
		printf "$b\n\n"
	fi

	printf "BLAKE3:\t "
	./b3sum "$f" 2>/dev/null | awk '{print $1}' | awk '{print $0}'

	printf "CRC32:\t "
	crc32 "$f" | awk '{print $0}'

	printf "MD5:\t "
	md5 -q "$f" | awk '{print $0}'

	printf "XXH:\t "
	./xxhsum "$f" 2>/dev/null | awk '{print $1}' | awk '{print $0}'

	if [ $optKeyDown -eq 0 ]
	then
		printf "SHA1:\t "
		shasum "$f" | awk '{print $1}' | awk '{print $0}'

		printf "SHA256:\t "
		shasum -a256 "$f" | awk '{print $1}' | awk '{print $0}'
	fi
	echo " "
done
